test run

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,8 +13,22 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/setup-env
       - uses: ./.github/actions/check-quality-gates
-        # read version number from file, increment it, and pass to gradlew
-        # write version file back; commit; tag
+      - name: Version Number Handling
+        id: step-version
+        #          chmod +x ./bin/version_increment_and_get.sh
+        run: |
+          newVersion=$(./bin/version_increment_and_get.sh)
+          rc=$?
+          if [ $rc -ne 0 ]; then
+            echo "version script failed with exit code $rc" >&2
+            exit $rc
+          fi
+          echo "new_version=$newVersion" >> $GITHUB_OUTPUT
+      - name: post msg
+        run: |
+          echo "New version to be released: ${{ steps.step-version.outputs.new_version }}"
+        # GIT commit changes: "auto release for version $newVersion"
+        # GIT tag with $newVersion
         # create GitHub release
         # matrix [macos, windows]:
         #    build artifact: run: ./gradlew packageDistributionForCurrentOS -Papp_version="${{ new_version }}"
